name: CI

on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn
      - name: Run Linter
        run: yarn lint .
      - name: Run Build
        run: yarn build